services:
  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: treading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: backend
    build:
      context: .
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: treading
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - 8081:8081

volumes:
  pgdata: