version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: treading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map 5432 on the host to 5432 on the container

volumes:
  pgdata:
