spring:
  application:
    name: coin

  datasource:
    url: jdbc:postgresql://localhost:5432/treading
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hogphat1607@gmail.com
    password: qpfmilrxltrdorhr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: redis
    port: 6379
    password: password
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8081
